preset: laravel

enabled:
  - alpha_ordered_imports
  - strict
  - strict_param
  - unalign_double_arrow

disabled:
  - length_ordered_imports
  - logical_not_operators_with_successor_space

finder:
  not-path:
    - resources/lang/da
    - resources/lang/es
    - resources/lang/fr
    - resources/lang/id
    - resources/lang/it
    - resources/lang/ja
    - resources/lang/ko
    - resources/lang/nl
    - resources/lang/pl
    - resources/lang/pt-br
    - resources/lang/ru
    - resources/lang/sv
    - resources/lang/vi
    - resources/lang/zh
    - resources/lang/zh-tw
