cache:
  directories:
    - vendor
    - node_modules
    - $HOME/.yarn-cache

dist: trusty
sudo: false

language: php

php:
  - 7.1

matrix:
  fast_finish: true

addons:
  apt:
    sources:
      - sourceline: 'deb http://repo.mysql.com/apt/ubuntu/ trusty mysql-5.7'
        key_url: 'https://gist.githubusercontent.com/nanaya/8c435175aa56da449f7ca485efdbac0f/raw/aac9f8352a91323fee72d8417fccaf8b3027f813/mysql-2017.key'
    packages:
      - mysql-community-server

env:
  global:
    - DB_USERNAME=root
    - SLACK_ENDPOINT=https://myconan.net/null/
    - PATH=$HOME/.yarn/bin:$PATH
    - APP_ENV=testing
    - SESSION_DRIVER=array
    - CACHE_DRIVER=array
    - CAMO_KEY=""
    - ES_VERSION=1.7.6 ES_DOWNLOAD_URL=https://download.elastic.co/elasticsearch/elasticsearch/elasticsearch-${ES_VERSION}.zip

install:
  - nvm install 8.9
  - nvm use 8.9
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.3.2
  - ./bin/db_setup.sh
  - ./build.sh

  # elasticsearch setup
  - wget "${ES_DOWNLOAD_URL}"
  - unzip "elasticsearch-${ES_VERSION}.zip"
  - ./"elasticsearch-${ES_VERSION}/bin/elasticsearch" &
  - sleep 10 # wait until the server is up
  - php artisan es:index-users --yes
  - php artisan es:index-documents --yes

script: ./bin/phpunit
