cache:
  directories:
    - vendor
    - node_modules
    - $HOME/.yarn-cache

dist: trusty
sudo: false

language: php

php:
  - 7.1

matrix:
  fast_finish: true

services:
  - redis-server

addons:
  apt:
    sources:
      - mysql-5.7-trusty
    packages:
      - mysql-server
  chrome: stable

env:
  global:
    - DB_USERNAME=root
    - SLACK_ENDPOINT=https://myconan.net/null/
    - PATH=$HOME/.yarn/bin:$PATH
    - APP_ENV=testing
    - SESSION_DRIVER=redis
    - CACHE_DRIVER=redis
    - CAMO_KEY=""
    - ES_VERSION=6.1.3 ES_DOWNLOAD_URL=https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-${ES_VERSION}.zip

install:
  - pecl install redis <<<''
  # elasticsearch setup (part 1)
  - travis_retry bash -c 'wget "${ES_DOWNLOAD_URL}"'
  - unzip "elasticsearch-${ES_VERSION}.zip"
  - ./"elasticsearch-${ES_VERSION}/bin/elasticsearch" &

  - travis_retry nvm install 8.9
  - nvm use 8.9
  - travis_retry bash -c 'curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.3.2'
  - ./bin/db_setup.sh
  - ./build.sh

  # elasticsearch setup (part 2)
  # wait until es server is up
  - wget -q --waitretry=1 --retry-connrefused -T 10 -O - http://127.0.0.1:9200
  - php artisan es:index-documents --yes

before_script:
  - google-chrome-stable --headless --disable-gpu --remote-debugging-port=9222 http://localhost &
  - php artisan serve > /dev/null 2>&1 &

jobs:
  include:
    - script: ./bin/phpunit
      name: "phpunit"
    - script: php artisan dusk --verbose
      name: "browser tests"
