preserve_hierarchy: true
files:
  - source: /resources/lang/en/**/*.php
    translation: /resources/lang/%locale%/**/%original_file_name%
    languages_mapping:
      locale:
        be-BY: be
        bg-BG: bg
        cs: cs
        da: da
        de: de
        el: el
        es-ES: es
        fi-FI: fi
        fi: fi
        fr: fr
        hu: hu
        id: id
        it: it
        ja: ja
        ko: ko
        nl: nl
        no-NO: no
        pl: pl
        pt-BR: pt-br
        pt-PT: pt
        ro-RO: ro
        ru: ru
        sk-SK: sk
        sv-SE: sv
        th: th
        tr: tr
        vi: vi
        zh-CN: zh
        zh-TW: zh-tw
