files:
  - source: /resources/lang/en/**/*.php
    translation: /resources/lang/%two_letters_code%/%original_file_name%
    languages_mapping:
      two_letters_code:
        zh-CN: zh
        pt-BR: pt-br
