version: '3.4'

x-env: &x-env
  CACHE_DRIVER: redis
  COMPOSER_HOME: /data/osuweb/.composer
  DB_HOST: osuweb-mysql
  ES_HOST: osuweb-es:9200
  HOME: /data/osuweb
  REDIS_HOST: osuweb-redis
  YARN_CACHE_FOLDER: /data/osuweb/.yarn

services:
  nginx:
    image: nginx:latest
    container_name: osuweb-nginx
    volumes:
      - ./docker/nginx/nginx-osu-next:/etc/nginx/conf.d/default.conf
      - .:/data/osuweb
    ports:
      - "8080:80"
  db:
    image: mysql:5.7
    container_name: osuweb-mysql
    volumes:
      - database:/var/lib/mysql
      - ./bin/db_setup.sh:/docker-entrypoint-initdb.d/db_setup.sh
      - ./docker/mysql/db_user.sql:/docker-entrypoint-initdb.d/db_user.sql
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_ONETIME_PASSWORD: "yes"
  redis:
    image: redis:latest
    container_name: osuweb-redis
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch-oss:6.2.1
    container_name: osuweb-es
    volumes:
      - elasticsearch:/usr/share/elasticsearch/data
    environment:
      discovery.type: single-node
  php:
    build:
      context: ./docker/php
    container_name: osuweb-php
    depends_on:
      - db
    working_dir: /data/osuweb
    volumes:
      - .:/data/osuweb
    user: $UID
    environment:
      <<: *x-env
    command: sh -c "(test -f .env || cp .env.example .env) && ./build.sh && php-fpm7 -y /data/osuweb/docker/php/php-fpm.conf"
  yarn:
    image: node:8-alpine
    container_name: osuweb-yarn
    volumes:
      - .:/data/osuweb
    environment:
      <<: *x-env
    user: $UID
    working_dir: /data/osuweb
    command: sh -c "yarn && yarn run watch"

volumes:
  database:
  elasticsearch:
