apiVersion: v1
kind: Secret
metadata:
  name: {{ include "osu-web-chart.fullname" . }}
  labels:
    {{- include "osu-web-chart.labels" . | nindent 4 }}
type: Opaque
stringData:
  .env: |
    APP_URL={{ .Values.config.laravel.url }}
    APP_ENV={{ .Values.config.laravel.env }}
    APP_DEBUG={{ .Values.config.laravel.debug }}
    APP_KEY={{ .Values.config.laravel.appKey }}
    APP_SENTRY={{ .Values.config.laravel.sentry.url }}
    APP_SENTRY_PUBLIC={{ .Values.config.laravel.sentry.public_url }}

    DB_HOST={{ .Values.config.db.host }}
    DB_DATABASE={{ .Values.config.db.database }}
    DB_USERNAME={{ .Values.config.db.user }}
    DB_PASSWORD={{ .Values.config.db.password }}

    REDIS_HOST={{ .Values.config.redis.app.host }}
    REDIS_PORT={{ .Values.config.redis.app.port }}
    REDIS_DB={{ .Values.config.redis.app.db }}

    CACHE_REDIS_HOST={{ .Values.config.redis.cache.host }}
    CACHE_REDIS_PORT={{ .Values.config.redis.cache.port }}
    CACHE_REDIS_DB={{ .Values.config.redis.cache.db }}

    MEMCACHED_PERSISTENT_ID={{ .Values.config.memcache.persistent_id }}
    MEMCACHED_USERNAME={{ .Values.config.memcache.username }}
    MEMCACHED_PASSWORD={{ .Values.config.memcache.password }}
    MEMCACHED_HOST={{ .Values.config.memcache.host }}
    MEMCACHED_PORT={{ .Values.config.memcache.port }}

    BROADCAST_DRIVER={{ .Values.config.laravel.log.driver }}
    CACHE_DRIVER={{ .Values.config.laravel.cache.driver }}
    CACHE_DRIVER_LOCAL={{ .Values.config.laravel.cache.localDriver }}
    SESSION_DRIVER={{ .Values.config.laravel.session.driver }}
    SESSION_DOMAIN={{ .Values.config.laravel.session.domain }}
    SESSION_SECURE_COOKIE={{ .Values.config.laravel.session.secureCookie }}

    MAIL_DRIVER={{ .Values.config.mail.driver }}
    MAIL_HOST={{ .Values.config.mail.host }}
    MAIL_PORT={{ .Values.config.mail.port }}
    MAIL_ENCRYPTION={{ .Values.config.mail.encryption }}
    MAIL_USERNAME={{ .Values.config.mail.username }}
    MAIL_PASSWORD={{ .Values.config.mail.password }}

    SHARED_INTEROP_SECRET={{ .Values.config.laravel.legacy.sharedInteropSecret }}

    FILESYSTEM_DISK={{ .Values.config.laravel.filesystem.disk }}

    BM_PROCESSOR_MIRRORS={{ .Values.config.beatmapsProcessor.mirrors }}
    BM_PROCESSOR_THUMBNAILER={{ .Values.config.beatmapsProcessor.thumbnailer }}
    BM_PROCESSOR_SENTRY={{ .Values.config.beatmapsProcessor.sentry }}

    S3_KEY={{ .Values.config.s3.default.key }}
    S3_SECRET={{ .Values.config.s3.default.secret }}
    S3_REGION={{ .Values.config.s3.default.region }}
    S3_BUCKET={{ .Values.config.s3.default.bucket }}

    S3_AVATAR_KEY={{ .Values.config.s3.avatar.key }}
    S3_AVATAR_SECRET={{ .Values.config.s3.avatar.secret }}
    S3_AVATAR_REGION={{ .Values.config.s3.avatar.region }}
    S3_AVATAR_BUCKET={{ .Values.config.s3.avatar.bucket }}
    AVATAR_STORAGE={{ .Values.config.s3.avatar.storage }}
    AVATAR_CACHE_PURGE_PREFIX={{ .Values.config.s3.avatar.cache_purge_prefix }}

    # Either "s3" or "local".
    SCORE_REPLAYS_STORAGE={{ .Values.config.laravel.scoreReplaysStorage }}

    QUEUE_DRIVER={{ .Values.config.laravel.queueDriver }}
    CAMO_KEY={{ .Values.config.laravel.camo.key }}
    CAMO_PREFIX={{ .Values.config.laravel.camo.prefix }}

    PASSPORT_KEY_PATH=/app/storage/passport

    GITHUB_TOKEN={{ .Values.config.laravel.githubToken }}

    DATADOG_ENABLED={{ .Values.config.laravel.datadog.enabled }}
    DATADOG_PREFIX={{ .Values.config.laravel.datadog.prefix }}
    DATADOG_API_KEY={{ .Values.config.laravel.datadog.apiKey }}
    DATADOG_APP_KEY={{ .Values.config.laravel.datadog.appKey }}
    DATADOG_HOST={{ .Values.config.laravel.datadog.host }}
    DATADOG_STATSD_HOST={{ .Values.config.laravel.datadog.statsd.host }}
    DATADOG_STATSD_PORT={{ .Values.config.laravel.datadog.statsd.port }}
    DATADOG_STATSD_SOCKET={{ .Values.config.laravel.datadog.statsd.socket }}

    CHANGELOG_GITHUB_TOKEN={{ .Values.config.laravel.changelogGithubToken }}

    PAYMENT_SANDBOX={{ .Values.config.laravel.payments.sandbox }}

    SHOPIFY_DOMAIN={{ .Values.config.laravel.payments.shopify.domain }}
    SHOPIFY_STOREFRONT_TOKEN={{ .Values.config.laravel.payments.shopify.storeFrontToken }}
    SHOPIFY_WEBHOOK_KEY={{ .Values.config.laravel.payments.shopify.webhookKey }}

    STORE_NOTIFICATION_CHANNEL={{ .Values.config.laravel.notifications.store.channel }}
    STORE_NOTIFICATIONS_QUEUE={{ .Values.config.laravel.notifications.store.queue }}
    STORE_STALE_DAYS={{ .Values.config.laravel.payments.storeStaleDays }}

    PAYPAL_URL={{ .Values.config.laravel.payments.paypal.url }}
    PAYPAL_MERCHANT_ID={{ .Values.config.laravel.payments.paypal.merchantId }}
    PAYPAL_CLIENT_ID={{ .Values.config.laravel.payments.paypal.clientId }}
    PAYPAL_CLIENT_SECRET={{ .Values.config.laravel.payments.paypal.clientSecret }}
    PAYPAL_NO_SHIPPING_EXPERIENCE_PROFILE_ID={{ .Values.config.laravel.payments.paypal.noShippingExperienceProfileId }}

    XSOLLA_API_KEY={{ .Values.config.laravel.payments.xsolla.apiKey }}
    XSOLLA_MERCHANT_ID={{ .Values.config.laravel.payments.xsolla.merchantId }}
    XSOLLA_PROJECT_ID={{ .Values.config.laravel.payments.xsolla.projectId }}
    XSOLLA_SECRET_KEY={{ .Values.config.laravel.payments.xsolla.secretKey }}

    CENTILI_API_KEY={{ .Values.config.laravel.payments.centili.apiKey }}
    CENTILI_SECRET_KEY={{ .Values.config.laravel.payments.centili.secretKey }}
    CENTILI_CONVERSION_RATE={{ .Values.config.laravel.payments.centili.conversionRate }}
    CENTILI_WIDGET_URL={{ .Values.config.laravel.payments.centili.widgetUrl }}

    ES_HOST={{ .Values.config.elasticsearch.host }}
    ES_SCORES_HOST={{ .Values.config.elasticsearch.scores.host }}
    ES_INDEX_PREFIX={{ .Values.config.elasticsearch.indexPrefix }}
    ES_CLIENT_TIMEOUT={{ .Values.config.elasticsearch.clientTimeout }}
    ES_CLIENT_CONNECT_TIMEOUT={{ .Values.config.elasticsearch.clientConnectTimeout }}
    ES_SEARCH_TIMEOUT={{ .Values.config.elasticsearch.searchTimeout }}

    NOTIFICATION_QUEUE={{ .Values.config.laravel.notifications.queue }}
    NOTIFICATION_REDIS_HOST={{ .Values.config.redis.notification.host }}
    NOTIFICATION_REDIS_PORT={{ .Values.config.redis.notification.port }}
    NOTIFICATION_REDIS_DB={{ .Values.config.redis.notification.db }}
    NOTIFICATION_ENDPOINT={{ .Values.config.notificationServer.publicUrl }}

    LOG_CHANNEL={{ .Values.config.laravel.logChannel }}

    #RECAPTCHA_SECRET={{ .Values.config.laravel.recaptcha.secret }}
    #RECAPTCHA_SITEKEY={{ .Values.config.laravel.recaptcha.siteKey }}
    #RECAPTCHA_THRESHOLD={{ .Values.config.laravel.recaptcha.threshold }}

    TWITCH_CLIENT_ID={{ .Values.config.laravel.twitch.clientId }}
    TWITCH_CLIENT_SECRET={{ .Values.config.laravel.twitch.clientSecret }}

    SCORES_ES_CACHE_DURATION={{ .Values.config.laravel.scores.cacheDuration }}
    SCORES_RANK_CACHE_LOCAL_SERVER={{ .Values.config.laravel.scoresRankCache.localServer }}
    SCORES_RANK_CACHE_MIN_USERS={{ .Values.config.laravel.scoresRankCache.minUsers }}
    SCORES_RANK_CACHE_SERVER_URL={{ .Values.config.laravel.scoresRankCache.serverUrl }}
    SCORES_RANK_CACHE_TIMEOUT={{ .Values.config.laravel.scoresRankCache.timeout }}

    BANCHO_BOT_USER_ID={{ .Values.config.laravel.legacy.banchoBotUserId }}

    {{ .Values.config.laravel.extraEnv }}
